### ISSUE TITLE
FR: multi style simultaneously

### ISSUE THREAD

**Issue by Lynx3x** [mdelobelle/obsidian_supercharged_links#152] opened 2022-10-27 08:01 UTC
situation: I have a file named "DEMO FILE", with tags "category/note" and "status/ongoing". I set the note tag with prefix "[note]", and the ongoing tag with prefix "[ongoing]" and yellow font color.

I want the file name shows like "[note][ongoing]DEMO FILE" with yellow color, but it seems like some conflicts. Prefix only shows one, and file name is in other font color(cause the note style has its own default color style)

Maybe add a feature that can auto detect and  combind prefix? and a switch on font color style?

**Comment by HEmile** [comment] 2022-10-28 07:39
Duplicate of #148

**Closed** 2022-10-28 07:39 UTC
