### ISSUE TITLE
ability to prepend multiple attributes / emojis to the link

### ISSUE THREAD

**Issue by sharetocreate** [mdelobelle/obsidian_supercharged_links#153] opened 2022-10-29 13:10 UTC
Trying to get two attributes - status, & type - to display their emojis before the name of the link - as shown on this section of bryan jenks workflow video - https://www.youtube.com/watch?v=wB89lJs5A3s&t=13679s

status is a coloured square emoji, and type is a descriptive emoji (video camera, book , etc) 

Both are set to prepend but only the most recent one shows. If i set to one to append they do show both

Is it possible to prepend two attributes? Tried all the options i can think of

Also noted that If it restart obisidan, my supercharged links / emojis disappear, until i reopen supercharge links options, and they return

If i change the order in options - i also get the same behaviour as the previous issue posted.

Supercharged Version 0.9.3 & Obsidian 1.0.3

Many thanks

**Comment by HEmile** [comment] 2022-10-29 18:25
Duplicate of #148

**Closed** 2022-10-29 18:25 UTC
