### ISSUE TITLE
[FR]: To add supercharged links for "backlinks in document"

### ISSUE THREAD

**Issue by cogscides** [mdelobelle/obsidian_supercharged_links#68] opened 2022-01-14 13:37 UTC
For now backlinks work only for backlinks which in sidebar. As a consistent feature will be good to have the same bahavior in the backlincks at the end of the document.
To show backlinks in document run command: `Backlinks: Toggle backlinks in document`

![image](https://user-images.githubusercontent.com/50235526/149523606-fc5a7efe-e176-4e10-a02f-742f4edad2c1.png)

**Comment by HEmile** [comment] 2022-01-14 13:55
Duplicate of #52 . It's in the planning!

**Closed by HEmile** 2022-01-14 13:55 UTC

**Comment by HEmile** [comment] 2022-01-27 21:54
Should work in latest version!
